services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-management-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:./hotel_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_H2_CONSOLE_ENABLED: "true"
      JWT_SECRET: ${JWT_SECRET}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST:-smtp.gmail.com}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT:-587}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_FROM: ${MAIL_USERNAME}
      CLOUDINARY_CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${API_KEY}
      CLOUDINARY_API_SECRET: ${API_SECRET}
      APP_PASSWORD_RESET_BASE_URL: ${PASSWORD_RESET_BASE_URL:-http://localhost:8080/reset-password}
    ports:
      - "8080:8080"
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/swagger-ui.html"]
      timeout: 10s
      retries: 5
      interval: 30s

networks:
  hotel-network:
    driver: bridge
