spring.application.name=HotelManagementSystem

spring.datasource.url=jdbc:h2:./hotel_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (useful for debugging - remove in production)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


## JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=nRVkanqskAVW7KiCa0ew060jNTDf1TBBwAJolzmq1z1
jwt.expiration=86400000

# Mailjet Configuration
mailjet.api-key=d57bc254ed8512fc98db4e09e14ac7d8
mailjet.secret-key=56d3a8abf31636790141c5db69ce00f0
mailjet.sender-email=noreply.app.testmail@gmail.com
mailjet.sender-name=Hotel Management System



# Cloudinary Configuration
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${API_KEY}
cloudinary.api-secret=${API_SECRET}

app.password-reset.base-url=${PASSWORD_RESET_BASE_URL:http://localhost:5173/auth/reset-password}
app.password-reset.expiration-minutes=30
