spring.application.name=HotelManagementSystem

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.mnehfmayulxrsjqzdfrn
spring.datasource.password=hotelmanagementsystemsamuel
spring.datasource.driver-class-name=org.postgresql.Driver


## JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=nRVkanqskAVW7KiCa0ew060jNTDf1TBBwAJolzmq1z1
jwt.expiration=86400000

# Mail (Gmail SMTP - update with your credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=${MAIL_USERNAME}


# Cloudinary Configuration
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${API_KEY}
cloudinary.api-secret=${API_SECRET}

app.password-reset.base-url=${PASSWORD_RESET_BASE_URL:http://localhost:8080/reset-password}
app.password-reset.expiration-minutes=30
