spring.application.name=HotelManagementSystem

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=samuel
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


## JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${jwtSecret}
jwt.expiration=86400000

# Mail (Gmail SMTP - update with your credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${mailUserName}
spring.mail.password= ${mailPassword}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=${mailUserName}


# Cloudinary Configuration
cloudinary.cloud-name= ${cloudName}
cloudinary.api-key=${apiKey}
cloudinary.api-secret=${apiSecret}

app.password-reset.base-url=${passwordResetBaseUrl:http://localhost:8080/reset-password}
app.password-reset.expiration-minutes=30
